# Alacritty Configuration File

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 5, y = 5 }
decorations = "buttonless"
opacity = 0.9


[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

# Font settings
[font]
normal.family = "ComicShannsMono Nerd Font"
bold.family = "ComicShannsMono Nerd Font"
italic.family = "ComicShannsMono Nerd Font"
size = 16.0

# Colors (based on Nord theme)  
[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "0x2E3440"
cursor = "0xD8DEE9"

[colors.selection]
text = "0x2E3440"
background = "0x4C566A"

[colors.normal]
black = "0x3B4252"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x8FBCBB"
white = "0xECEFF4"

# Shell settings
[terminal.shell]
program = "ubuntu"


